// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOJPfXER5pluZv1nkgiyEhxK83RI9px4',
    appId: '1:876189597350:web:c588b74182b76ba9d83e67',
    messagingSenderId: '876189597350',
    projectId: 'rca-demo-db',
    authDomain: 'rca-demo-db.firebaseapp.com',
    storageBucket: 'rca-demo-db.firebasestorage.app',
    measurementId: 'G-7X7D41V1XD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8uvP5sMzUQlY1ICQI-y_KoPLSP7QRxmM',
    appId: '1:876189597350:android:880c78cc652c3c98d83e67',
    messagingSenderId: '876189597350',
    projectId: 'rca-demo-db',
    storageBucket: 'rca-demo-db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNkNsj-2p-qMypQxC_mOtRcDFGCWyXEWY',
    appId: '1:876189597350:ios:09fbdefc6ceb7758d83e67',
    messagingSenderId: '876189597350',
    projectId: 'rca-demo-db',
    storageBucket: 'rca-demo-db.firebasestorage.app',
    iosBundleId: 'com.example.reseauxCommissionApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNkNsj-2p-qMypQxC_mOtRcDFGCWyXEWY',
    appId: '1:876189597350:ios:09fbdefc6ceb7758d83e67',
    messagingSenderId: '876189597350',
    projectId: 'rca-demo-db',
    storageBucket: 'rca-demo-db.firebasestorage.app',
    iosBundleId: 'com.example.reseauxCommissionApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyOJPfXER5pluZv1nkgiyEhxK83RI9px4',
    appId: '1:876189597350:web:f657dd711ffc2011d83e67',
    messagingSenderId: '876189597350',
    projectId: 'rca-demo-db',
    authDomain: 'rca-demo-db.firebaseapp.com',
    storageBucket: 'rca-demo-db.firebasestorage.app',
    measurementId: 'G-EWFY9H1XQZ',
  );
}
